[package]
name = "zkevm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halo2-snark-aggregator-circuit = { git = "https://github.com/scroll-tech/halo2-snark-aggregator", branch = "test/gpu" }
halo2-snark-aggregator-solidity = { git = "https://github.com/scroll-tech/halo2-snark-aggregator", branch = "test/gpu" }
halo2-snark-aggregator-api = { git = "https://github.com/scroll-tech/halo2-snark-aggregator", branch = "test/gpu" }

pairing = { git = 'https://github.com/appliedzkp/pairing', package = "pairing_bn256", tag = "v0.1.1" }
halo2_proofs = { git = "https://github.com/scroll-tech/halo2-gpu.git", branch = "common_rs" }
bus-mapping = { git = "https://github.com/scroll-tech/zkevm-circuits.git", branch = "test/gpu" }
eth-types = { git = "https://github.com/scroll-tech/zkevm-circuits.git", branch = "test/gpu" }
zkevm-circuits = { git = "https://github.com/scroll-tech/zkevm-circuits.git", branch = "test/gpu", features = ["test"] }
halo2-mpt-circuits = { git = "https://github.com/scroll-tech/mpt-circuit.git", branch = "test/gpu" }
rand = "0.8"
rand_xorshift = "0.3"
is-even = "1.0.0"
ethers-core = "0.6.0"
hex = "0.4.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.66"
types = { path = "../types", features = ["test"] }
log = "0.4"
anyhow = "1.0"
num-bigint = "0.4.3"
blake2 = "0.10.3"
dotenv = "0.15.0"
env_logger = "0.9.0"
strum = "0.24"
strum_macros = "0.24"
once_cell = "1.8.0"
chrono = "0.4.19"

[target.'cfg(target_os = "linux")'.dependencies]
procfs = "0.13.0"

[features]
default = []
prove_verify = []
